/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vilae_saquicelaj_sh;

import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonna
 */
public class Isla extends javax.swing.JFrame {

    JLabel lbBarcoUno;
    JLabel lbBarcoDos;
    JLabel lbBarcoTres;
    JLabel lbIsla;
    JLabel lbPuerto;

    HiloBarcoUno hB1;
    HiloBarcoDos hB2;
    HiloBarcoTres hB3;

    Icon imgBarcoUno;
    Icon imgBarcoDos;
    Icon imgBarcoTres;
    Icon imgIsla;
    Icon imgOceano;

    Isla islita;
    IslaNaufragos iNaufragos;

    Boolean inicioJuego = false;
    Boolean pause = false;

    /**
     * Creates new form Isla
     */
    public Isla() {
        initComponents();
        iniciarImgs();
        islita = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBUno = new javax.swing.JPanel();
        pBDos = new javax.swing.JPanel();
        pBTres = new javax.swing.JPanel();
        pPuerto = new javax.swing.JPanel();
        pIsla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbNaufragos = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbTiempoRestante = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtBUCapacidad = new javax.swing.JTextField();
        txtBDCapacidad = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtBTCapacidad = new javax.swing.JTextField();
        btIniciar = new javax.swing.JButton();
        btParar = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtCapacidadIsla = new javax.swing.JTextField();
        lbB1Estado = new javax.swing.JLabel();
        lbB1Tiempo = new javax.swing.JLabel();
        lbB1Naufragos = new javax.swing.JLabel();
        lbB1Capacidad = new javax.swing.JLabel();
        lbB2Estado = new javax.swing.JLabel();
        lbB2Tiempo = new javax.swing.JLabel();
        lbB2Naufragos = new javax.swing.JLabel();
        lbB2Capacidad = new javax.swing.JLabel();
        lbB3Estado = new javax.swing.JLabel();
        lbB3Tiempo = new javax.swing.JLabel();
        lbB3Naufragos = new javax.swing.JLabel();
        lbB3Capacidad = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBUTiempo = new javax.swing.JTextField();
        txtBDTiempo = new javax.swing.JTextField();
        txtBTTiempo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pBUno.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout pBUnoLayout = new javax.swing.GroupLayout(pBUno);
        pBUno.setLayout(pBUnoLayout);
        pBUnoLayout.setHorizontalGroup(
            pBUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        pBUnoLayout.setVerticalGroup(
            pBUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        pBDos.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout pBDosLayout = new javax.swing.GroupLayout(pBDos);
        pBDos.setLayout(pBDosLayout);
        pBDosLayout.setHorizontalGroup(
            pBDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        pBDosLayout.setVerticalGroup(
            pBDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        pBTres.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout pBTresLayout = new javax.swing.GroupLayout(pBTres);
        pBTres.setLayout(pBTresLayout);
        pBTresLayout.setHorizontalGroup(
            pBTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        pBTresLayout.setVerticalGroup(
            pBTresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        pPuerto.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout pPuertoLayout = new javax.swing.GroupLayout(pPuerto);
        pPuerto.setLayout(pPuertoLayout);
        pPuertoLayout.setHorizontalGroup(
            pPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        pPuertoLayout.setVerticalGroup(
            pPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        pIsla.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pIslaLayout = new javax.swing.GroupLayout(pIsla);
        pIsla.setLayout(pIslaLayout);
        pIslaLayout.setHorizontalGroup(
            pIslaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        pIslaLayout.setVerticalGroup(
            pIslaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Barco 1");

        jLabel2.setText("Estado");

        jLabel3.setText("Tiempo");

        jLabel4.setText("Naufragos");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Barco 2");

        jLabel6.setText("Estado");

        jLabel7.setText("Tiempo");

        jLabel8.setText("Naufragos");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Barco 3");

        jLabel10.setText("Personas");

        lbNaufragos.setText("0");

        jLabel12.setText("Estado");

        jLabel13.setText("Capacidad");

        jLabel14.setText("Tiempo");

        lbTiempoRestante.setText("0");

        jLabel15.setText("ms");

        jLabel16.setText("Capacidad");

        jLabel17.setText("Tiempo");

        jLabel18.setText("Nafragos");

        jLabel19.setText("Capacidad");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Barco Uno");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Barco Dos");

        jLabel22.setText("Capacidad");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Barco Tres");

        btIniciar.setText("Iniciar");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        btParar.setText("Parar");
        btParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPararActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Isla");

        jLabel27.setText("Capacidad");

        txtCapacidadIsla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacidadIslaActionPerformed(evt);
            }
        });

        lbB1Estado.setText("Esperando");

        lbB1Tiempo.setText("00:00");

        lbB1Naufragos.setText("00");

        lbB1Capacidad.setText("0");

        lbB2Estado.setText("Esperando");

        lbB2Tiempo.setText("00:00");

        lbB2Naufragos.setText("00");

        lbB2Capacidad.setText("0");

        lbB3Estado.setText("Esperando");

        lbB3Tiempo.setText("00:00");

        lbB3Naufragos.setText("00");

        lbB3Capacidad.setText("0");

        jLabel11.setText("Tiempo ( s )");

        txtBTTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBTTiempoActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pBDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbB2Naufragos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbB2Capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lbB3Naufragos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbB3Tiempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbB3Estado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel24))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBTCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBUCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBDCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pBUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbB1Naufragos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbB2Tiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbB2Estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbB1Capacidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbB1Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbB1Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pBTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(lbB3Capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btIniciar)
                                .addGap(31, 31, 31)
                                .addComponent(btParar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBUTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBDTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCapacidadIsla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBTTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbNaufragos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pIsla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbTiempoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)))))
                        .addGap(0, 35, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(lbNaufragos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(lbB1Estado))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(lbB1Tiempo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(lbB1Naufragos))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel13)
                                            .addComponent(lbB1Capacidad)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pIsla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(lbTiempoRestante)
                                    .addComponent(jLabel15))))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel22))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBDCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(txtBDTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btIniciar)
                                    .addComponent(btParar))
                                .addContainerGap(88, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pBUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pBDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(lbB2Estado))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(lbB2Tiempo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel26)
                                            .addComponent(lbB2Naufragos))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel16)
                                            .addComponent(txtBUCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel27)
                                            .addComponent(txtCapacidadIsla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbB2Capacidad)
                                            .addComponent(jLabel20)
                                            .addComponent(txtBUTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pBTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(lbB3Estado))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17)
                                            .addComponent(lbB3Tiempo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18)
                                            .addComponent(lbB3Naufragos)
                                            .addComponent(jLabel24)
                                            .addComponent(txtBTCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBTTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19)
                                            .addComponent(lbB3Capacidad)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        if (inicioJuego) {
            pause = false;
            
        } else {
            this.btParar.setEnabled(true);
            controlErrores();
        }
    }//GEN-LAST:event_btIniciarActionPerformed

    private void txtCapacidadIslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacidadIslaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadIslaActionPerformed

    private void btPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPararActionPerformed
        pause = true;
    }//GEN-LAST:event_btPararActionPerformed

    private void txtBTTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBTTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBTTiempoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Isla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Isla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Isla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Isla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Isla().setVisible(true);
            }
        });
    }

    // ------ Metodos -----
    public void iniciarImgs() {

        //  Barco UNO
        ImageIcon icono = new ImageIcon("barcoUno.jpg");

        lbBarcoUno = new JLabel();
        lbBarcoUno.setBounds(0, 0, this.pBUno.getWidth(), this.pBUno.getHeight());
        this.pBUno.add(lbBarcoUno);

        imgBarcoUno = new ImageIcon(icono.getImage().getScaledInstance(this.lbBarcoUno.getWidth(),
                this.lbBarcoUno.getHeight(),
                Image.SCALE_DEFAULT));
        lbBarcoUno.setIcon(imgBarcoUno);

        //  BARCO DOS
        icono = new ImageIcon("barcoDos.png");
        lbBarcoDos = new JLabel();
        lbBarcoDos.setBounds(0, 0, this.pBDos.getWidth(), this.pBDos.getHeight());
        this.pBDos.add(lbBarcoDos);

        imgBarcoDos = new ImageIcon(icono.getImage().getScaledInstance(this.lbBarcoDos.getWidth(),
                this.lbBarcoDos.getHeight(),
                Image.SCALE_DEFAULT));
        lbBarcoDos.setIcon(imgBarcoDos);

        //  BARCO TRES
        icono = new ImageIcon("barcoTres.png");
        lbBarcoTres = new JLabel();
        lbBarcoTres.setBounds(0, 0, this.pBTres.getWidth(), this.pBTres.getHeight());
        this.pBTres.add(lbBarcoTres);

        imgBarcoTres = new ImageIcon(icono.getImage().getScaledInstance(this.lbBarcoTres.getWidth(),
                this.lbBarcoTres.getHeight(),
                Image.SCALE_DEFAULT));
        lbBarcoTres.setIcon(imgBarcoTres);

        //  Isla
        icono = new ImageIcon("isla.jpg");
        lbIsla = new JLabel();
        lbIsla.setBounds(0, 0, this.pIsla.getWidth(), this.pIsla.getHeight());
        this.pIsla.add(lbIsla);

        imgIsla = new ImageIcon(icono.getImage().getScaledInstance(this.pIsla.getWidth(),
                this.pIsla.getHeight(),
                Image.SCALE_DEFAULT));
        lbIsla.setIcon(imgIsla);

        // PUERTO
        icono = new ImageIcon("oceano.jpg");
        lbPuerto = new JLabel();
        lbPuerto.setBounds(0, 0, this.pPuerto.getWidth(), this.pPuerto.getHeight());
        this.pPuerto.add(lbPuerto);

        imgOceano = new ImageIcon(icono.getImage().getScaledInstance(this.lbPuerto.getWidth(),
                this.lbPuerto.getHeight(),
                Image.SCALE_DEFAULT));
        lbPuerto.setIcon(imgOceano);

    }

    public void llegarIsla(int barco, int limite) {
        switch (barco) {
            case 1:
                lbPuerto.setIcon(imgBarcoUno);
                this.lbB1Estado.setText("Ocupado");
                this.lbB1Naufragos.setText(String.valueOf(limite));
                System.out.println("Se desocupo el barco Uno");
                break;

            case 2:
                lbPuerto.setIcon(imgBarcoDos);
                this.lbB2Estado.setText("Ocupado");
                this.lbB2Naufragos.setText(String.valueOf(limite));
                System.out.println("Se desocupo el barco Dos");
                break;

            case 3:
                lbPuerto.setIcon(imgBarcoTres);
                this.lbB3Estado.setText("Ocupado");
                this.lbB3Naufragos.setText(String.valueOf(limite));
                System.out.println("Se desocupo el barco Tres");
                break;
        }

        this.lbNaufragos.setText(String.valueOf(iNaufragos.getNumNaufragos()));
        repaint();
    }   
   
    public void espera(int barco) {
        switch (barco) {
            case 1:
                this.lbB1Estado.setText("Esperando");
                break;
            case 2:
                this.lbB2Estado.setText("Esperando");
                break;
            case 3:
                this.lbB3Estado.setText("Esperando");
                break;

        }
    }

    public void controlErrores() {

        if (this.txtBUCapacidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Dato incompleto! \nBarco 1");
            this.txtBUCapacidad.setFocusable(true);
            return;
        }

        if (this.txtBDCapacidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Dato incompleto! \nBarco 2");
            this.txtBUCapacidad.setFocusable(true);
            return;
        }

        if (this.txtBDCapacidad.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Dato incompleto! \nBarco 3");
            this.txtBTCapacidad.setFocusable(true);
            return;
        }
        // TIEMPO
        if (this.txtBUTiempo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Dato incompleto! \nBarco 1");
            this.txtBUTiempo.setFocusable(true);
            return;
        }

        if (this.txtBDTiempo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Dato incompleto! \nBarco 2");
            this.txtBUTiempo.setFocusable(true);
            return;
        }

        if (this.txtBTTiempo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Dato incompleto!\nBarco 3");
            this.txtBTTiempo.setFocusable(true);
            return;
        }
        //CAPACIDAD ISLA
        if (this.txtCapacidadIsla.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Dato incompleto Capacidad Isla!");
            //this.txtCapacidadIsla.setCursor();

            return;
        }

        inicioJuego = true;
        iniciaElJuego();

    }

    public void iniciaElJuego() {
        int numNaufragos = Integer.valueOf(this.txtCapacidadIsla.getText());
        int limiteB1 = Integer.valueOf(this.txtBUCapacidad.getText());
        int limiteB2 = Integer.valueOf(this.txtBDCapacidad.getText());
        int limiteB3 = Integer.valueOf(this.txtBTCapacidad.getText());

        int tB1 = Integer.valueOf(this.txtBUTiempo.getText());
        int tB2 = Integer.valueOf(this.txtBDTiempo.getText());
        int tB3 = Integer.valueOf(this.txtBTTiempo.getText());

        this.lbNaufragos.setText(txtCapacidadIsla.getText());

        iNaufragos = new IslaNaufragos(islita, numNaufragos);
        hB1 = new HiloBarcoUno(iNaufragos, limiteB1, tB1);
        hB2 = new HiloBarcoDos(iNaufragos, limiteB2, tB2);
        hB3 = new HiloBarcoTres(iNaufragos, limiteB3, tB3);

        hB1.start();
        hB2.start();
        hB3.start();

        // Inicio de Tablas
        // BARCO 1
        this.lbB1Capacidad.setText(String.valueOf(limiteB1));
        this.lbB1Tiempo.setText(String.valueOf(tB1));

        //BARCO 2
        this.lbB2Capacidad.setText(String.valueOf(limiteB2));
        this.lbB2Tiempo.setText(String.valueOf(tB2));

        //BARCO 3
        this.lbB3Capacidad.setText(String.valueOf(limiteB3));
        this.lbB3Tiempo.setText(String.valueOf(tB3));

        // this.lbB1Capacidad.setText(this.txtBDCapacidad.getTex());
        //this.lbB1Tiempo.setText(String.valueOf(this.txtBDTiempo.getTex()));
    }

    public void sinNaufragos() {
        if (!pause) {
            JOptionPane.showMessageDialog(null, "Se han rescatado todos los naufragos :)");
            System.out.println("Sin naufragos");
            this.lbB1Estado.setText("Finalizado");
            this.lbB2Estado.setText("Finalizado");
            this.lbB3Estado.setText("Finalizado");
            this.lbNaufragos.setText("0");
            pause = true;
            lbPuerto.setIcon(imgOceano);
            repaint();
            this.btParar.setEnabled(false);
            this.inicioJuego = false;
            hB1.stop();
            hB2.stop();
            hB3.stop();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIniciar;
    private javax.swing.JButton btParar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbB1Capacidad;
    private javax.swing.JLabel lbB1Estado;
    private javax.swing.JLabel lbB1Naufragos;
    private javax.swing.JLabel lbB1Tiempo;
    private javax.swing.JLabel lbB2Capacidad;
    private javax.swing.JLabel lbB2Estado;
    private javax.swing.JLabel lbB2Naufragos;
    private javax.swing.JLabel lbB2Tiempo;
    private javax.swing.JLabel lbB3Capacidad;
    private javax.swing.JLabel lbB3Estado;
    private javax.swing.JLabel lbB3Naufragos;
    private javax.swing.JLabel lbB3Tiempo;
    private javax.swing.JLabel lbNaufragos;
    private javax.swing.JLabel lbTiempoRestante;
    private javax.swing.JPanel pBDos;
    private javax.swing.JPanel pBTres;
    private javax.swing.JPanel pBUno;
    private javax.swing.JPanel pIsla;
    private javax.swing.JPanel pPuerto;
    private javax.swing.JTextField txtBDCapacidad;
    private javax.swing.JTextField txtBDTiempo;
    private javax.swing.JTextField txtBTCapacidad;
    private javax.swing.JTextField txtBTTiempo;
    private javax.swing.JTextField txtBUCapacidad;
    private javax.swing.JTextField txtBUTiempo;
    private javax.swing.JTextField txtCapacidadIsla;
    // End of variables declaration//GEN-END:variables
}
